{% set name = "conda-project" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 787474eb84547cacf51b854bfc5c5fe079f38c77a4e24f33432fbce2b5cf0bd5

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  number: 0
  entry_points:
    - conda-project = conda_project.cli.main:main

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs >=0.3
    - setuptools-scm >=7.1
  run:
    - python
    - conda-lock >=2.5.6
    - lockfile
    - pexpect
    - ruamel.yaml
    - pydantic
    - shellingham
    - python-dotenv
    - fsspec
    - python-libarchive-c
    - setuptools
    - libarchive-c
    - ruamel_yaml

test:
  requires:
    - pip
  imports:
    - conda_project
  commands:
    - pip check
    - conda-project --help
    - python -c "import conda_project; ver = conda_project.__version__; assert ver == \"{{ version }}\""

about:
  home: https://github.com/conda-incubator/conda-project
  summary: Tool for encapsulating, running, and reproducing projects with conda environments
  description: |
    Sharing your work is more than sharing your code in a script file or notebook. To make your
    work properly reproducible, it is necessary to include the list of required third-party
    dependencies, specifications for how to run your code, and any other files that it may need.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://conda-incubator.github.io/conda-project/user_guide.html
  dev_url: https://github.com/conda-incubator/conda-project

extra:
  recipe-maintainers:
    - AlbertDeFusco
    - mattkram
